### ISSUE TITLE
omniORB port does not compile on ubuntu 9.10 (Trac #611)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#610]
port install ends with:

In file included from include.c:30:
def.h:131: error: conflicting types for ‘getline’
/usr/include/stdio.h:651: note: previous declaration of ‘getline’ was here
make[3]: *** [include.o] Error 1
make[3]: Leaving directory `/home/boersma/Work/Software/I3_PORTS/var/db/dports/build/file._home_boersma_Work_Software_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_lib_omniorb_4.0.7/work/omniORB-4.0.7/src/tool/omkdepend'
make[2]: *** [export] Error 1
make[2]: Leaving directory `/home/boersma/Work/Software/I3_PORTS/var/db/dports/build/file._home_boersma_Work_Software_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_lib_omniorb_4.0.7/work/omniORB-4.0.7/src/tool'
make[1]: *** [export] Error 1
make[1]: Leaving directory `/home/boersma/Work/Software/I3_PORTS/var/db/dports/build/file._home_boersma_Work_Software_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_lib_omniorb_4.0.7/work/omniORB-4.0.7/src'
make: *** [all] Error 1

Migrated from https://code.icecube.wisc.edu/ticket/611
```json
{
    "status": "closed", 
    "changetime": "2010-05-05T15:27:41", 
    "description": "port install ends with:\n\nIn file included from include.c:30:\ndef.h:131: error: conflicting types for \u2018getline\u2019\n/usr/include/stdio.h:651: note: previous declaration of \u2018getline\u2019 was here\nmake[3]: *** [include.o] Error 1\nmake[3]: Leaving directory `/home/boersma/Work/Software/I3_PORTS/var/db/dports/build/file._home_boersma_Work_Software_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_lib_omniorb_4.0.7/work/omniORB-4.0.7/src/tool/omkdepend'\nmake[2]: *** [export] Error 1\nmake[2]: Leaving directory `/home/boersma/Work/Software/I3_PORTS/var/db/dports/build/file._home_boersma_Work_Software_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_lib_omniorb_4.0.7/work/omniORB-4.0.7/src/tool'\nmake[1]: *** [export] Error 1\nmake[1]: Leaving directory `/home/boersma/Work/Software/I3_PORTS/var/db/dports/build/file._home_boersma_Work_Software_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_lib_omniorb_4.0.7/work/omniORB-4.0.7/src'\nmake: *** [all] Error 1\n", 
    "reporter": "boersma", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1273073261000000", 
    "component": "tools/ports", 
    "summary": "omniORB port does not compile on ubuntu 9.10", 
    "priority": "minor", 
    "keywords": "ports jeb karmic omniorb", 
    "time": "2010-04-30T06:44:08", 
    "milestone": "", 
    "owner": "nega", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20100504T15:34:35: 
* troy changed component from "booking" to "tools"
* troy changed owner from "blaufuss" to "nega"
* troy commented:

> breakage confirmed.   
> should ask Torsten if he wants to upgrading any time soon.   
> 
> For the time being a sane error message would work.
> 
>

**Comment by icecube-trac** [comment]
Trac update at 20100504T15:48:11: nega commented:

> See ticket:264

**Comment by icecube-trac** [comment]
Trac update at 20100505T15:27:41: 
* nega changed resolution from "" to "fixed"
* nega commented:

> Fixed. Do 'port sync' followed by 'port install omniorb_4.0.7'.


* nega changed status from "new" to "closed"
