### ISSUE TITLE
dataclasses does not build with Boost>1.47 (Trac #832)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#826]
I am trying to build the trunk version of simulation but cannot get dataclasses to compile.  The problem is with I3MCTree.cxx under pybindings.  The error is associated with Boost's python function range.  I have tried all versions of Boost on our machines (1.47.0, 1.51.0, 1.52.0, 1.55.0, 1.57.0) and the error is the same.  The output I get from running cmake is:

```text

[ 40%] Building CXX object dataclasses/CMakeFiles/dataclasses-pybindings.dir/private/pybindings/I3MCTree.cxx.o
/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx: In function ‘I3Particle* at2(I3MCTree&, int)’:
/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:83: warning: comparison between signed and unsigned integer expressions
/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:87: warning: comparison between signed and unsigned integer expressions
/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/range/algorithm/equal.hpp: In function ‘void register_I3MCTree()’:
/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/range/algorithm/equal.hpp:160: error: ‘boost::range’ is not a function,
/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/python/iterator.hpp:112: error:   conflict with ‘template<class NextPolicies, class Target, class Accessor1, class Accessor2> boost::python::api::object boost::python::range(Accessor1, Accessor2, NextPolicies*, boost::type<U>*)’
/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:247: error:   in call to ‘range’
/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/range/algorithm/equal.hpp:160: error: ‘boost::range’ is not a function,
/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/python/iterator.hpp:112: error:   conflict with ‘template<class NextPolicies, class Target, class Accessor1, class Accessor2> boost::python::api::object boost::python::range(Accessor1, Accessor2, NextPolicies*, boost::type<U>*)’
/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:262: error:   in call to ‘range’
/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/range/algorithm/equal.hpp:160: error: ‘boost::range’ is not a function,
/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/python/iterator.hpp:112: error:   conflict with ‘template<class NextPolicies, class Target, class Accessor1, class Accessor2> boost::python::api::object boost::python::range(Accessor1, Accessor2, NextPolicies*, boost::type<U>*)’
/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:281: error:   in call to ‘range’
make[2]: *** [dataclasses/CMakeFiles/dataclasses-pybindings.dir/private/pybindings/I3MCTree.cxx.o] Error 1
make[1]: *** [dataclasses/CMakeFiles/dataclasses-pybindings.dir/all] Error 2
make: *** [all] Error 2

```

This error only started during the simulation workshop.  Before then everything built without any errors.  

Other possible useful information:
compiler: gcc-4.4.5
cmake: 2.8.5
os: RHEL 6.5

Migrated from https://code.icecube.wisc.edu/ticket/832
```json
{
    "status": "closed", 
    "changetime": "2015-01-26T22:20:20", 
    "description": "I am trying to build the trunk version of simulation but cannot get dataclasses to compile.  The problem is with I3MCTree.cxx under pybindings.  The error is associated with Boost's python function range.  I have tried all versions of Boost on our machines (1.47.0, 1.51.0, 1.52.0, 1.55.0, 1.57.0) and the error is the same.  The output I get from running cmake is:\n\n{{{\n\n[ 40%] Building CXX object dataclasses/CMakeFiles/dataclasses-pybindings.dir/private/pybindings/I3MCTree.cxx.o\n/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx: In function \u2018I3Particle* at2(I3MCTree&, int)\u2019:\n/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:83: warning: comparison between signed and unsigned integer expressions\n/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:87: warning: comparison between signed and unsigned integer expressions\n/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/range/algorithm/equal.hpp: In function \u2018void register_I3MCTree()\u2019:\n/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/range/algorithm/equal.hpp:160: error: \u2018boost::range\u2019 is not a function,\n/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/python/iterator.hpp:112: error:   conflict with \u2018template<class NextPolicies, class Target, class Accessor1, class Accessor2> boost::python::api::object boost::python::range(Accessor1, Accessor2, NextPolicies*, boost::type<U>*)\u2019\n/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:247: error:   in call to \u2018range\u2019\n/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/range/algorithm/equal.hpp:160: error: \u2018boost::range\u2019 is not a function,\n/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/python/iterator.hpp:112: error:   conflict with \u2018template<class NextPolicies, class Target, class Accessor1, class Accessor2> boost::python::api::object boost::python::range(Accessor1, Accessor2, NextPolicies*, boost::type<U>*)\u2019\n/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:262: error:   in call to \u2018range\u2019\n/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/range/algorithm/equal.hpp:160: error: \u2018boost::range\u2019 is not a function,\n/opt/software/boost/1.55.0--GCC-4.4.5--OpenMPI-1.4.3/include/boost/python/iterator.hpp:112: error:   conflict with \u2018template<class NextPolicies, class Target, class Accessor1, class Accessor2> boost::python::api::object boost::python::range(Accessor1, Accessor2, NextPolicies*, boost::type<U>*)\u2019\n/mnt/home/hignight/work/simulation_workshop/trunk/dataclasses/private/pybindings/I3MCTree.cxx:281: error:   in call to \u2018range\u2019\nmake[2]: *** [dataclasses/CMakeFiles/dataclasses-pybindings.dir/private/pybindings/I3MCTree.cxx.o] Error 1\nmake[1]: *** [dataclasses/CMakeFiles/dataclasses-pybindings.dir/all] Error 2\nmake: *** [all] Error 2\n\n}}}\n\nThis error only started during the simulation workshop.  Before then everything built without any errors.  \n\nOther possible useful information:\ncompiler: gcc-4.4.5\ncmake: 2.8.5\nos: RHEL 6.5", 
    "reporter": "hignight", 
    "cc": "david.schultz@icecube.wisc.edu", 
    "resolution": "fixed", 
    "_ts": "1422310820471928", 
    "component": "combo simulation", 
    "summary": "dataclasses does not build with Boost>1.47", 
    "priority": "critical", 
    "keywords": "dataclasses", 
    "time": "2014-12-16T19:46:27", 
    "milestone": "", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150122T19:59:58: 
* david.schultz changed cc from "" to "david.schultz@icecube.wisc.edu"
* david.schultz commented:

> Is this still a problem?

**Comment by icecube-trac** [comment]
Trac update at 20150126T22:20:20: 
* david.schultz changed status from "new" to "closed"
* david.schultz changed resolution from "" to "fixed"
* david.schultz commented:

> Reproduced on SL6 with boost 1.57
> 
> Seems to be an issue with the new I3MCTree iterator pybindings.
> 
> Fixed in r128197/IceCube.
