### ISSUE TITLE
pybindings/I3Time.cxx does not compile on RHEL4/SL4 (python 2.3.4) (Trac #548)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#547]
I am getting this compile error with the trunk of offline-software (SVN revision 54071)

[ 56%] Building CXX object dataclasses/private/pybindings/CMakeFiles/dataclasses-pybindings.dir/I3Time.cxx.o
/net/user/boersma/icetray/offline-
    trunk/src/dataclasses/private/pybindings/I3Time.cxx: In function
   `boost::python::api::object GetDateTime(const I3Time &)':
/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:55:
    error: `PyDateTime_FromDateAndTime' was not declared in this scope
/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:55:
    warning: unused variable 'PyDateTime_FromDateAndTime'
/net/user/boersma/icetray/offline-
    trunk/src/dataclasses/private/pybindings/I3Time.cxx: In function
   `I3Time GetI3Time(const boost::python::api::object &)':
/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:67:
    error: `PyDateTime_DateTimeType' was not declared in this scope
/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:78:
    error: `PyDateTime_DateType' was not declared in this scope
/net/user/boersma/icetray/offline-
    trunk/src/dataclasses/private/pybindings/I3Time.cxx: In function
   `void register_I3Time()':
/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:96:
    error: `PyDateTime_IMPORT' was not declared in this scope
/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:96:
    warning: unused variable 'PyDateTime_IMPORT'
make[2]: *** [dataclasses/private/pybindings/CMakeFiles/dataclasses-pybindings.dir/I3Time.cxx.o] Error 1
make[1]: *** [dataclasses/private/pybindings/CMakeFiles/dataclasses-pybindings.dir/all] Error 2
make: *** [all] Error 2

Migrated from https://code.icecube.wisc.edu/ticket/548
```json
{
    "status": "closed", 
    "changetime": "2009-04-16T21:53:52", 
    "description": "I am getting this compile error with the trunk of offline-software (SVN revision 54071)\n\n[ 56%] Building CXX object dataclasses/private/pybindings/CMakeFiles/dataclasses-pybindings.dir/I3Time.cxx.o\n/net/user/boersma/icetray/offline-\n    trunk/src/dataclasses/private/pybindings/I3Time.cxx: In function\n   `boost::python::api::object GetDateTime(const I3Time &)':\n/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:55:\n    error: `PyDateTime_FromDateAndTime' was not declared in this scope\n/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:55:\n    warning: unused variable 'PyDateTime_FromDateAndTime'\n/net/user/boersma/icetray/offline-\n    trunk/src/dataclasses/private/pybindings/I3Time.cxx: In function\n   `I3Time GetI3Time(const boost::python::api::object &)':\n/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:67:\n    error: `PyDateTime_DateTimeType' was not declared in this scope\n/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:78:\n    error: `PyDateTime_DateType' was not declared in this scope\n/net/user/boersma/icetray/offline-\n    trunk/src/dataclasses/private/pybindings/I3Time.cxx: In function\n   `void register_I3Time()':\n/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:96:\n    error: `PyDateTime_IMPORT' was not declared in this scope\n/net/user/boersma/icetray/offline-trunk/src/dataclasses/private/pybindings/I3Time.cxx:96:\n    warning: unused variable 'PyDateTime_IMPORT'\nmake[2]: *** [dataclasses/private/pybindings/CMakeFiles/dataclasses-pybindings.dir/I3Time.cxx.o] Error 1\nmake[1]: *** [dataclasses/private/pybindings/CMakeFiles/dataclasses-pybindings.dir/all] Error 2\nmake: *** [all] Error 2\n", 
    "reporter": "boersma", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1239918832000000", 
    "component": "IceTray", 
    "summary": "pybindings/I3Time.cxx does not compile on RHEL4/SL4 (python 2.3.4)", 
    "priority": "major", 
    "keywords": "compile python DateTime pybindings", 
    "time": "2009-04-09T09:55:08", 
    "milestone": "", 
    "owner": "troy", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20090416T21:53:52: 
* troy changed resolution from "" to "fixed"
* troy commented:

> TWhitehorn got this one:   the interface needed here only came available in python 2.4.  Made the conversion-to/from python datetime conditional on availability of py>=2.4
> 
> fixed in dataclasses r54351


* troy changed status from "new" to "closed"
