### ISSUE TITLE
[clsim] compatibility with geant4.10.3 (Trac #1986)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1978]
```text
/cvmfs/icecube.opensciencegrid.org/py2-v3/metaprojects/combo/stable/clsim/private/geant4/TrkEMPhysicsUHE.cxx: In member function ‘virtual void TrkEMPhysicsUHE::ConstructProcess()’:
/cvmfs/icecube.opensciencegrid.org/py2-v3/metaprojects/combo/stable/clsim/private/geant4/TrkEMPhysicsUHE.cxx:63:37: error: ‘class G4LossTableManager’ has no member named ‘SetMaxEnergy’
     G4LossTableManager::Instance()->SetMaxEnergy(10.*PeV);
```

Would be nice to fix this soon and get it in a simulation point release, so it will build with py2-v3.

Migrated from https://code.icecube.wisc.edu/ticket/1986
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:53", 
    "description": "{{{\n/cvmfs/icecube.opensciencegrid.org/py2-v3/metaprojects/combo/stable/clsim/private/geant4/TrkEMPhysicsUHE.cxx: In member function \u2018virtual void TrkEMPhysicsUHE::ConstructProcess()\u2019:\n/cvmfs/icecube.opensciencegrid.org/py2-v3/metaprojects/combo/stable/clsim/private/geant4/TrkEMPhysicsUHE.cxx:63:37: error: \u2018class G4LossTableManager\u2019 has no member named \u2018SetMaxEnergy\u2019\n     G4LossTableManager::Instance()->SetMaxEnergy(10.*PeV);\n}}}\n\nWould be nice to fix this soon and get it in a simulation point release, so it will build with py2-v3.", 
    "reporter": "david.schultz", 
    "cc": "olivas", 
    "resolution": "fixed", 
    "_ts": "1550067233566919", 
    "component": "combo simulation", 
    "summary": "[clsim] compatibility with geant4.10.3", 
    "priority": "critical", 
    "keywords": "", 
    "time": "2017-04-20T22:05:47", 
    "milestone": "", 
    "owner": "claudio.kopper", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20170421T13:38:40: jgonzalez commented:

> For the record... this is in TrkEMPhysicsUHE. This class does nothing but extend the range of its base class, which might not be the best way to do it to begin with. If you comment out that SetMaxEnergy line, you end up with an empty class.
> 
> I could look into it at some point in my life.

**Comment by icecube-trac** [comment]
Trac update at 20170421T17:19:39: 
* claudio.kopper commented:

> In changeset 155194:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="155194"
> Remove TrkEMPhysicsUHE which wasn't used by the Geant4 code anyway and would not compile with Geant4.10.3. This change has absolutely no implications on Geant4 as the code in question was never run anyway. fixes #1978.
> ```


* claudio.kopper changed resolution from "" to "fixed"
* claudio.kopper changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:53: 
* olivas commented:

> Milestone May 2017 deleted


* olivas changed milestone from "May 2017" to ""
