### ISSUE TITLE
Steamshovel doesn't compile with python 3.4.2 (Trac #827)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#821]
Compiling http://code.icecube.wisc.edu/svn/projects/steamshovel/releases/V14-11-00 I got the following error message:

```text
/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:
    In static member function ‘static void * scripting::shovelart
    ::QStringConversion::convertible(PyObject *)’:
/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:210:32:
    error: ‘PyString_Check’ was not declared in this scope
return PyString_Check(obj_ptr) ? obj_ptr : 0;
^
/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:
    In static member function ‘static void scripting::shovelart
    ::QStringConversion::construct(
        PyObject *, boost::python::converter::rvalue_from_python_stage1_data
        *)’:
/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:215:50:
    error: ‘PyString_AsString’ was not declared in this scope
const char * value = PyString_AsString( obj_ptr );
^
/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:
    In static member function ‘static void * scripting::shovelart
    ::QStringConversion::convertible(PyObject *)’:
/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:211:2:
    warning: control reaches end of non-void function [-Wreturn-type]
}
^
steamshovel/CMakeFiles/shovelart-pybindings.dir/build.make:169: recipe for target 'steamshovel/CMakeFiles/shovelart-pybindings.dir/private/shovelart/pybindings/Types.cpp.o' failed
```

Googling the error I found http://permalink.gmane.org/gmane.comp.debugging.sigrok.devel/57 which proposes a patch that should be usable by us:
```#!cpp
/* re-define some String functions for recent python (>= 3.0) */
#if PY_VERSION_HEX >= 0x03000000
#define PyString_AsString PyBytes_AsString
#define PyString_FromString PyBytes_FromString
#define PyString_Check PyBytes_Check
#endif
```

For my local copy I put it in the beginning of steamshovel/private/shovelart/pybindings/Types.cpp and it compiled, but I am not sure that is the best place to put it... or if version checked is the "good" value.

Migrated from https://code.icecube.wisc.edu/ticket/827
```json
{
    "status": "closed", 
    "changetime": "2015-07-22T20:05:18", 
    "description": "Compiling http://code.icecube.wisc.edu/svn/projects/steamshovel/releases/V14-11-00 I got the following error message:\n{{{\n/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:\n    In static member function \u2018static void * scripting::shovelart\n    ::QStringConversion::convertible(PyObject *)\u2019:\n/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:210:32:\n    error: \u2018PyString_Check\u2019 was not declared in this scope\nreturn PyString_Check(obj_ptr) ? obj_ptr : 0;\n^\n/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:\n    In static member function \u2018static void scripting::shovelart\n    ::QStringConversion::construct(\n        PyObject *, boost::python::converter::rvalue_from_python_stage1_data\n        *)\u2019:\n/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:215:50:\n    error: \u2018PyString_AsString\u2019 was not declared in this scope\nconst char * value = PyString_AsString( obj_ptr );\n^\n/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:\n    In static member function \u2018static void * scripting::shovelart\n    ::QStringConversion::convertible(PyObject *)\u2019:\n/home/jp/IceCube/svn/icerec/steamshovel/private/shovelart/pybindings/Types.cpp:211:2:\n    warning: control reaches end of non-void function [-Wreturn-type]\n}\n^\nsteamshovel/CMakeFiles/shovelart-pybindings.dir/build.make:169: recipe for target 'steamshovel/CMakeFiles/shovelart-pybindings.dir/private/shovelart/pybindings/Types.cpp.o' failed\n}}}\n\nGoogling the error I found http://permalink.gmane.org/gmane.comp.debugging.sigrok.devel/57 which proposes a patch that should be usable by us:\n{{{#!cpp\n/* re-define some String functions for recent python (>= 3.0) */\n#if PY_VERSION_HEX >= 0x03000000\n#define PyString_AsString PyBytes_AsString\n#define PyString_FromString PyBytes_FromString\n#define PyString_Check PyBytes_Check\n#endif\n}}}\n\nFor my local copy I put it in the beginning of steamshovel/private/shovelart/pybindings/Types.cpp and it compiled, but I am not sure that is the best place to put it... or if version checked is the \"good\" value.", 
    "reporter": "jpa14", 
    "cc": "david.schultz@icecube.wisc.edu", 
    "resolution": "fixed", 
    "_ts": "1437595518711454", 
    "component": "combo reconstruction", 
    "summary": "Steamshovel doesn't compile with python 3.4.2", 
    "priority": "minor", 
    "keywords": "python3 steamshovel", 
    "time": "2014-12-09T22:34:52", 
    "milestone": "", 
    "owner": "hdembinski", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150211T21:14:54: 
* olivas changed owner from "" to "david.schultz"
* olivas changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20150721T22:49:04: 
* david.schultz changed owner from "david.schultz" to "hdembinski"
* david.schultz changed cc from "" to "david.schultz@icecube.wisc.edu"
* david.schultz commented:

> not sure if this is still an issue?

**Comment by icecube-trac** [comment]
Trac update at 20150722T01:10:55: hdembinski commented:

> an interesting proposed solution, worth a try. we already have the pycompat header for this sort of thing.

**Comment by icecube-trac** [comment]
Trac update at 20150722T15:35:46: jpa14 commented:

> I rechecked today with python 3.4.3 and the problem still existed. I had to move the above mentioned code from Types.cpp to private/scripting/qstring_converter.h when I updated steamshovel trunk.

**Comment by icecube-trac** [comment]
Trac update at 20150722T20:05:18: 
* hdembinski changed resolution from "" to "fixed"
* hdembinski changed status from "assigned" to "closed"
* hdembinski commented:

> In changeset 135479:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="135479"
> make steamshovel compatible with Python 3.4, closes #821
> ```
