### ISSUE TITLE
[dataio-shovel] segfaults when opening i3files (Trac #2408)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2400]
Migrated from https://code.icecube.wisc.edu/ticket/2408
```json
{
    "status": "assigned", 
    "changetime": "2020-07-14T15:13:51", 
    "description": "Opening an i3file with a fresh build of combo.trunk (r178839) using py3-v4.0.1 results in a Segmentation fault:\n\n{{{\n************************************************************************\n*                                                                      *\n*                   W E L C O M E  to  I C E T R A Y                   *\n*                                                                      *\n*                   Version combo.trunk     r178839                    *\n*                                                                      *\n*                You are welcome to visit our Web site                 *\n*                        http://icecube.umd.edu                        *\n*                                                                      *\n************************************************************************\n\nIcetray environment has:\n   I3_SRC       = /scratch/eganster/software/meta-projects/combo/trunk/src\n   I3_BUILD     = /scratch/eganster/software/meta-projects/combo/trunk/build_py3-v4.0.1\n   I3_TESTDATA  = /cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/../data/i3-test-data-svn/trunk\n   Python       = 3.6.8\n\neganster@cobalt03 ~ $ dataio-shovel /cvmfs/icecube.opensciencegrid.org/data/GCD/GeoCalibDetectorStatus_AVG_55697-57531_PASS2_SPE_withScaledNoise.i3.gz\nSegmentation fault\n}}}", 
    "reporter": "eganster", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1594739631904109", 
    "component": "cvmfs", 
    "summary": "[dataio-shovel] segfaults when opening i3files", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2020-02-05T20:41:17", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "david.schultz", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20200205T20:41:49: 
* olivas changed priority from "normal" to "blocker"
* olivas changed milestone from "" to "Vernal Equinox 2020"

**Comment by icecube-trac** [comment]
Trac update at 20200205T21:21:55: david.schultz commented:

> Bad library?
> 
> 
> ```text
> (gdb) bt
> https://code.icecube.wisc.edu/ticket/0  0x00007ffff770e32b in newterm_sp () from /cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/libncurses.so.6
> #1  0x00007ffff770e7db in newterm () from /cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/libncurses.so.6
> #2  0x00007ffff7709a8d in initscr () from /cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/libncurses.so.6
> #3  0x0000000000524351 in View::start (this=0x573e40 <View::Instance()::the_view>) at /scratch/dschultz/combo/trunk/dataio/private/shovel/View.cxx:124
> #4  0x00000000004cd971 in main (argc=2, argv=0x7fffffffd1a8) at /scratch/dschultz/combo/trunk/dataio/private/shovel/Controller.cxx:285
> ```

**Comment by icecube-trac** [comment]
Trac update at 20200205T22:51:27: david.schultz commented:

> The py3-v4.0.1 dataio-shovel links against libform twice, once from the system and once from CVMFS.  Since this seemed odd, I removed the `-lform -ltinfo` flags and dataio-shovel started working again.
> 
> Not sure what to do with this.

**Comment by icecube-trac** [comment]
Trac update at 20200217T19:47:08: 
* olivas changed status from "new" to "accepted"
* olivas changed owner from "" to "olivas"

**Comment by icecube-trac** [comment]
Trac update at 20200217T19:55:07: olivas changed summary from "dataio-shovel segfaults when opening i3files" to "[dataio-shovel] segfaults when opening i3files"

**Comment by icecube-trac** [comment]
Trac update at 20200218T14:25:30: 
* olivas changed status from "accepted" to "closed"
* olivas commented:

> Looks like this was fixed?  We can always reopen if this reappears.


* olivas changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20200219T14:57:53: 
* eganster commented:

> I just tested again with a fresh build of combo.trunk (r178988) and `dataio-shovel` still segfauults...
> However, removing the `-lform -ltinfo` flags in https://code.icecube.wisc.edu/projects/icecube/browser/IceCube/meta-projects/combo/trunk/dataio/CMakeLists.txt#L51 nake it working again.


* eganster changed status from "closed" to "reopened"
* eganster changed resolution from "fixed" to ""

**Comment by icecube-trac** [comment]
Trac update at 20200220T12:19:06: eganster commented:

> dataio-shovel is linked twice against different versions of libform and libncurses:
> libform.so.5 and libncurses.so.5 from the system and libform.so.6 and libncurses.so.6 from the cvmfs.
> libtinfo.so.5 from the system is always included, regardless of setting the `-ltinfo` flag or not.
> However, explicitly including it results in a segfault of dataio-shovel whereas it runs fine in the other case (w/o the flag).
> No idea why... (see also [https://code.icecube.wisc.edu/projects/icecube/changeset/179003/IceCube r179003] in the snobo branch)

**Comment by icecube-trac** [comment]
Trac update at 20200220T17:12:55: kjmeagher commented:

> Why were `-lform -ltinfo` even added to dataio's CMakeLists.txt like this in the first place? We use cmake's `find_package(Curses)` which should detect everything needed to link against curses. If that is wrong we need to fix that. Alternaivly the problem could be with whatever is going on in lines 37-80 of in https://code.icecube.wisc.edu/projects/icecube/browser/IceCube/meta-projects/combo/trunk/cmake/tools/ncurses.cmake  in which case we need to fix that

**Comment by icecube-trac** [comment]
Trac update at 20200220T17:29:00: david.schultz commented:

> I believe they were hacks for specific OS versions.  Not intended as long-term fixes, just short-term patches.  But you know how that goes.

**Comment by icecube-trac** [comment]
Trac update at 20200302T16:54:58: olivas changed status from "reopened" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20200302T16:59:46: kjmeagher commented:

> A good place to start with this would be to determine if `find_package(Curses)` is setting the `CURSES_LIBRARIES` variable correctly on whichever platform is requiring `-ltinfo`.

**Comment by icecube-trac** [comment]
Trac update at 20200305T15:45:33: kjmeagher commented:

> The issue here is that `find_package(Curses)` sets `CURSES_LIBRARIES` to `/usr/lib64/libcurses.so;/usr/lib64/libform.so` and `CURSES_LIBRARY` to `/usr/lib64/libcurses.so`. Presumably on the platform that dschultz has neglected to name `CURSES_LIBRARIES` also includes `libtinfo`. 
> 
> The correct fix is to change the macros defined in `cmake/project.cmake` from using `*_LIBRARY` to `*_LIBRARIES`.

**Comment by icecube-trac** [comment]
Trac update at 20200305T20:31:34: nega changed owner from "olivas" to "nega"

**Comment by icecube-trac** [comment]
Trac update at 20200309T14:36:45: olivas commented:

> The build of dataio-shovel is temporarily disabled.  On cobalt cvmfs py3-v4.1.0 I get the following error when building the trunk:
> 
> 
> ```text
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: CMakeFiles/dataio-shovel.dir/private/shovel/View.cxx.o: in function `boost::optional<unsigned int> View::dialog<unsigned int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x3f): undefined reference to `new_field'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x50): undefined reference to `set_field_back'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x57): undefined reference to `TYPE_INTEGER'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x6f): undefined reference to `set_field_type'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x7f): undefined reference to `set_field_buffer'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x90): undefined reference to `new_form'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xba): undefined reference to `set_form_win'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xe2): undefined reference to `set_form_sub'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x14c): undefined reference to `post_form'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x17e): undefined reference to `form_driver'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x191): undefined reference to `form_driver'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1a9): undefined reference to `form_driver'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1b4): undefined reference to `field_buffer'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1ce): undefined reference to `unpost_form'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1d6): undefined reference to `free_form'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4View6dialogIjEEN5boost8optionalIT_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1df): undefined reference to `free_field'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: CMakeFiles/dataio-shovel.dir/private/shovel/View.cxx.o: in function `boost::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > View::dialog<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x51): undefined reference to `new_field'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x63): undefined reference to `set_field_back'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x6a): undefined reference to `TYPE_REGEXP'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x7b): undefined reference to `set_field_type'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x8c): undefined reference to `set_field_buffer'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x9f): undefined reference to `new_form'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0xc9): undefined reference to `set_form_win'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0xf1): undefined reference to `set_form_sub'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x15b): undefined reference to `post_form'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x18e): undefined reference to `form_driver'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x1a1): undefined reference to `form_driver'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x1b9): undefined reference to `form_driver'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x1c5): undefined reference to `field_buffer'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x424): undefined reference to `unpost_form'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x42c): undefined reference to `free_form'
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: View.cxx:(.text._ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_[_ZN4View6dialogINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost8optionalIT_EERKS6_]+0x436): undefined reference to `free_field'
> collect2: error: ld returned 1 exit status
> 
> ```

**Comment by icecube-trac** [comment]
Trac update at 20200309T16:50:37: kjmeagher commented:

> In changeset 179333:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="179333"
> put a bandaid on linking with ncurses, this works with cvmfs py3-v4.1.0	and macos.
> See #2400
> ```

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas commented:

> Milestone Vernal Equinox 2020 deleted


* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"

**Comment by icecube-trac** [comment]
Trac update at 20200702T16:13:11: olivas commented:

> I think the problem is in ncurses.cmake.  NCURSES_LIBRARIES is set to CURSES_LIBRARIES (set by FindCurses.cmake) only if NOT CURSES_FOUND, which makes little sense.
> 
> Moving that outside the if block that seems to work just fine on py3-v4.0.1 (after also removing the hack in dataio/CMakeLists.txt).
> 
> ncurses.cmake could use a scrubbing, so I'm gonna do that now.  If cmake can't find ncurses then I think we bail as opposed to trying to shim something up.  It's not clear to my why we were doing this anyway and there are no comments in the cmake file to explain the rationale.

**Comment by icecube-trac** [comment]
Trac update at 20200702T16:23:54: 
* olivas commented:

> In changeset 180870:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="180870"
> go all-in with cmake find_package.  fixes #2400.
> ```


* olivas changed resolution from "" to "fixed"
* olivas changed status from "accepted" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20200702T17:06:04: 
* olivas commented:

> It's still not usable in cvmfs py3-v4.0.1 in Madison.  There's a conflict in ncurses shared library versions.  cdk it seems was built against system ncurses whereas dataio-shovel builds against cvmfs ncurses.
> 
> /cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-lh5ncjznzy34ztyisj5w2aytsqhz47i5/bin/ld: warning: libncurses.so.5, needed by /cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/libcdk.so, may conflict with libncurses.so.6
> 
> 
> 
> 


* olivas changed status from "closed" to "reopened"
* olivas changed resolution from "fixed" to ""

**Comment by icecube-trac** [comment]
Trac update at 20200702T17:06:25: 
* olivas changed owner from "nega" to "david.schultz"
* olivas changed status from "reopened" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20200702T17:52:47: olivas commented:

> Same issue with py3-v4.1.0.
> 
> Seems like spack issue now.
> 
> 
> ```text
> [100%] Linking CXX executable ../bin/dataio-shovel
> /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/binutils-2.31.1-oydtl3oxhodbpc2f5quwodv7rl4rhqcv/bin/ld: warning: libncurses.so.5, needed by /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/libcdk.so, may conflict with libncurses.so.6
> [100%] Built target dataio-shovel
> olivas@cobalt06 /scratch/olivas/icecube/combo/trunk/build_pv3-v4.1.0 $ ldd /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/libcdk.so
> 	linux-vdso.so.1 =>  (0x00007ffea4b89000)
> 	libc.so.6 => /usr/lib64/libc.so.6 (0x00007fcabbe6e000)
> 	libncurses.so.5 => /usr/lib64/libncurses.so.5 (0x00007fcabbc47000)
> 	libtinfo.so.5 => /usr/lib64/libtinfo.so.5 (0x00007fcabba1c000)
> 	/lib64/ld-linux-x86-64.so.2 (0x000055f476b18000)
> 	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007fcabb818000)
> ```

**Comment by icecube-trac** [comment]
Trac update at 20200714T15:13:51: 
* olivas commented:

> I think the solution here is to either remove ncurses from cvmfs and force people to build against system ncurses (like cvmfs cdk does) or build cvmfs/spack cdk against cvmfs/spack ncurses to keep things consistent.


* olivas changed component from "combo core" to "cvmfs"
