### ISSUE TITLE
ports fail to compile on ubuntu 8.10 x86_64 (Trac #154)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#154]
Running make to compile the ports source, I get

....

make[2]: Leaving directory `/a/klas/icecube/port_source/src/package1.0'
===> making all in src/pextlib1.0
make[2]: Entering directory `/a/klas/icecube/port_source/src/pextlib1.0'
gcc -c -DUSE_TCL_STUBS -W -Wall -pedantic -g -O2 -DHAVE_CONFIG_H -I.. -I. -I"/usr/include/tcl8.4" -DHAVE_LIMITS_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DHAVE_PTHREAD_ATTR_SETSTACKSIZE=1 -DHAVE_PTHREAD_ATFORK=1 -DTCL_THREADS=1 -DPEEK_XCLOSEIM=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_IS_LONG=1 -DHAVE_GETCWD=1 -DHAVE_OPENDIR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_STRTOLL=1 -DHAVE_STRTOULL=1 -DHAVE_TMPNAM=1 -DHAVE_WAITPID=1 -DHAVE_GETPWUID_R_5=1 -DHAVE_GETPWUID_R=1 -DHAVE_GETPWNAM_R_5=1 -DHAVE_GETPWNAM_R=1 -DHAVE_GETGRGID_R_5=1 -DHAVE_GETGRGID_R=1 -DHAVE_GETGRNAM_R_5=1 -DHAVE_GETGRNAM_R=1 -DHAVE_GETHOSTBYNAME_R_6=1 -DHAVE_GETHOSTBYNAME_R=1 -DHAVE_GETHOSTBYADDR_R_8=1 -DHAVE_GETHOSTBYADDR_R=1 -DUSE_TERMIOS=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_TM_ZONE=1 -DHAVE_GMTIME_R=1 -DHAVE_LOCALTIME_R=1 -DHAVE_TM_GMTOFF=1 -DHAVE_TIMEZONE_VAR=1 -DHAVE_ST_BLKSIZE=1 -DSTDC_HEADERS=1 -DHAVE_SIGNED_CHAR=1 -DHAVE_LANGINFO=1 -DHAVE_SYS_IOCTL_H=1 -fPIC xinstall.c -o xinstall.o
xinstall.c: In function ‘InstallCmd’:
xinstall.c:142: warning: unused variable ‘flags’
xinstall.c: In function ‘install’:
xinstall.c:422: warning: unused parameter ‘fset’
xinstall.c: In function ‘create_newfile’:
xinstall.c:856: warning: unused parameter ‘sbp’
xinstall.c: In function ‘trymmap’:
xinstall.c:1091: warning: unused parameter ‘fd’
xinstall.c: In function ‘InstallCmd’:
xinstall.c:344: warning: ‘fset’ may be used uninitialized in this function
In function ‘open’,
    inlined from ‘create_newfile’ at xinstall.c:900,
    inlined from ‘install’ at xinstall.c:524:make[2]: Leaving directory `/a/klas/icecube/port_source/src/package1.0'
/usr/include/bits/fcntl2.h:45: error: call to ‘__open_too_many_args’ declared with attribute error: open can be called either with 2 or 3 arguments, not more
/usr/include/bits/fcntl2.h:45: error: call to ‘__open_too_many_args’ declared with attribute error: open can be called either with 2 or 3 arguments, not more
make[2]: *** [xinstall.o] Error 1
make[2]: Leaving directory `/a/klas/icecube/port_source/src/pextlib1.0'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/a/klas/icecube/port_source/src'
make: *** [all] Error 1

Migrated from https://code.icecube.wisc.edu/ticket/154
```json
{
    "status": "closed", 
    "changetime": "2009-03-06T01:48:15", 
    "description": "  Running make to compile the ports source, I get\n\n....\n\nmake[2]: Leaving directory `/a/klas/icecube/port_source/src/package1.0'\n===> making all in src/pextlib1.0\nmake[2]: Entering directory `/a/klas/icecube/port_source/src/pextlib1.0'\ngcc -c -DUSE_TCL_STUBS -W -Wall -pedantic -g -O2 -DHAVE_CONFIG_H -I.. -I. -I\"/usr/include/tcl8.4\" -DHAVE_LIMITS_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DHAVE_PTHREAD_ATTR_SETSTACKSIZE=1 -DHAVE_PTHREAD_ATFORK=1 -DTCL_THREADS=1 -DPEEK_XCLOSEIM=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_IS_LONG=1 -DHAVE_GETCWD=1 -DHAVE_OPENDIR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_STRTOLL=1 -DHAVE_STRTOULL=1 -DHAVE_TMPNAM=1 -DHAVE_WAITPID=1 -DHAVE_GETPWUID_R_5=1 -DHAVE_GETPWUID_R=1 -DHAVE_GETPWNAM_R_5=1 -DHAVE_GETPWNAM_R=1 -DHAVE_GETGRGID_R_5=1 -DHAVE_GETGRGID_R=1 -DHAVE_GETGRNAM_R_5=1 -DHAVE_GETGRNAM_R=1 -DHAVE_GETHOSTBYNAME_R_6=1 -DHAVE_GETHOSTBYNAME_R=1 -DHAVE_GETHOSTBYADDR_R_8=1 -DHAVE_GETHOSTBYADDR_R=1 -DUSE_TERMIOS=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_TM_ZONE=1 -DHAVE_GMTIME_R=1 -DHAVE_LOCALTIME_R=1 -DHAVE_TM_GMTOFF=1 -DHAVE_TIMEZONE_VAR=1 -DHAVE_ST_BLKSIZE=1 -DSTDC_HEADERS=1 -DHAVE_SIGNED_CHAR=1 -DHAVE_LANGINFO=1 -DHAVE_SYS_IOCTL_H=1 -fPIC xinstall.c -o xinstall.o\nxinstall.c: In function \u2018InstallCmd\u2019:\nxinstall.c:142: warning: unused variable \u2018flags\u2019\nxinstall.c: In function \u2018install\u2019:\nxinstall.c:422: warning: unused parameter \u2018fset\u2019\nxinstall.c: In function \u2018create_newfile\u2019:\nxinstall.c:856: warning: unused parameter \u2018sbp\u2019\nxinstall.c: In function \u2018trymmap\u2019:\nxinstall.c:1091: warning: unused parameter \u2018fd\u2019\nxinstall.c: In function \u2018InstallCmd\u2019:\nxinstall.c:344: warning: \u2018fset\u2019 may be used uninitialized in this function\nIn function \u2018open\u2019,\n    inlined from \u2018create_newfile\u2019 at xinstall.c:900,\n    inlined from \u2018install\u2019 at xinstall.c:524:make[2]: Leaving directory `/a/klas/icecube/port_source/src/package1.0'\n/usr/include/bits/fcntl2.h:45: error: call to \u2018__open_too_many_args\u2019 declared with attribute error: open can be called either with 2 or 3 arguments, not more\n/usr/include/bits/fcntl2.h:45: error: call to \u2018__open_too_many_args\u2019 declared with attribute error: open can be called either with 2 or 3 arguments, not more\nmake[2]: *** [xinstall.o] Error 1\nmake[2]: Leaving directory `/a/klas/icecube/port_source/src/pextlib1.0'\nmake[1]: *** [all] Error 1\nmake[1]: Leaving directory `/a/klas/icecube/port_source/src'\nmake: *** [all] Error 1", 
    "reporter": "klas", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1236304095000000", 
    "component": "tools/ports", 
    "summary": "ports fail to compile on ubuntu 8.10 x86_64", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2008-11-19T02:42:53", 
    "milestone": "", 
    "owner": "cgils", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20090306T01:48:15: 
* blaufuss commented:

> this works now.  We have test machines with these tools installed.  Should have been closed earlier.


* blaufuss changed status from "new" to "closed"
* blaufuss changed resolution from "" to "fixed"
