### ISSUE TITLE
Steamshovel does not compile with boost 1.38.0 (Trac #1038)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1032]
Icerec trunk r134527, steamshovel shows following error when compiling

```text
[  0%] Checking build against environment
[  0%] Built target env-check
[ 21%] Built target icetray
[ 32%] Built target dataclasses
[ 32%] Building CXX object steamshovel/CMakeFiles/shovelio.dir/private/shovelio/File.cpp.o
/afs/ifh.de/group/amanda/scratch/hpbretz/software/icerec/trunk/src/steamshovel/
    private/shovelio/File.cpp: In constructor ‘shovelio::raw::File::File(
        const string &, shovelio::raw::File::Type)’:
/afs/ifh.de/group/amanda/scratch/hpbretz/software/icerec/trunk/src/steamshovel/private/shovelio/File.cpp:41:
    error: ‘never_close_handle’ is not a member of ‘boost::iostreams’
make[3]: *** [steamshovel/CMakeFiles/shovelio.dir/private/shovelio/File.cpp.o] Error 1
make[2]: *** [steamshovel/CMakeFiles/shovelio.dir/all] Error 2
make[1]: *** [steamshovel/CMakeFiles/steamshovel.dir/rule] Error 2
make: *** [steamshovel] Error 2
```

Migrated from https://code.icecube.wisc.edu/ticket/1038
```json
{
    "status": "closed", 
    "changetime": "2015-06-30T09:24:09", 
    "description": "Icerec trunk r134527, steamshovel shows following error when compiling\n\n{{{\n[  0%] Checking build against environment\n[  0%] Built target env-check\n[ 21%] Built target icetray\n[ 32%] Built target dataclasses\n[ 32%] Building CXX object steamshovel/CMakeFiles/shovelio.dir/private/shovelio/File.cpp.o\n/afs/ifh.de/group/amanda/scratch/hpbretz/software/icerec/trunk/src/steamshovel/\n    private/shovelio/File.cpp: In constructor \u2018shovelio::raw::File::File(\n        const string &, shovelio::raw::File::Type)\u2019:\n/afs/ifh.de/group/amanda/scratch/hpbretz/software/icerec/trunk/src/steamshovel/private/shovelio/File.cpp:41:\n    error: \u2018never_close_handle\u2019 is not a member of \u2018boost::iostreams\u2019\nmake[3]: *** [steamshovel/CMakeFiles/shovelio.dir/private/shovelio/File.cpp.o] Error 1\nmake[2]: *** [steamshovel/CMakeFiles/shovelio.dir/all] Error 2\nmake[1]: *** [steamshovel/CMakeFiles/steamshovel.dir/rule] Error 2\nmake: *** [steamshovel] Error 2\n}}}", 
    "reporter": "hbretz", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1435656249169722", 
    "component": "combo reconstruction", 
    "summary": "Steamshovel does not compile with boost 1.38.0", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2015-06-30T09:18:33", 
    "milestone": "", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150630T09:24:09: 
* jvansanten changed status from "new" to "closed"
* jvansanten changed resolution from "" to "fixed"
* jvansanten commented:

> In changeset 134563:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="134563"
> Use old iostream ctor arguments with boost < 1.44. Closes #1032.
> ```


* jvansanten changed owner from "" to "jvansanten"
