### ISSUE TITLE
libarchive does not build with gcc 4.6.0 (Trac #650)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#649]
$I3_PORTS/bin/port install libarchive

results in this error:

```text
[ 47%] Building C object libarchive/CMakeFiles/archive.dir/archive_write_set_format_shar.c.o
/home/boersma/Work/icetray/I3_PORTS/var/db/dports/build/file._home_boersma_Work_icetray_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_archivers_libarchive/work/libarchive-2.8.4/libarchive/archive_write_set_format_shar.c: In function \u2018uuencode_line\u2019:
/home/boersma/Work/icetray/I3_PORTS/var/db/dports/build/file._home_boersma_Work_icetray_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_archivers_libarchive/work/libarchive-2.8.4/libarchive/archive_write_set_format_shar.c:412:7: error: variable \u2018tmp_buf\u2019 set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

make[2]: *** [libarchive/CMakeFiles/archive.dir/archive_write_set_format_shar.c.o] Error 1
make[1]: *** [libarchive/CMakeFiles/archive.dir/all] Error 2
make: *** [all] Error 2
```

The offending lines of code does not seem to be completely harmless
(quoting lines 411-443 of archive_write_set_format_shar.c):

```text
#!C
{
        // char tmp_buf[3], *buf;
        char tmp_buf[3], *buf;
        size_t alloc_len;

        /* len <= 45 -> expanded to 60 + len byte + new line */
        alloc_len = shar->work.length + 62;
        if (archive_string_ensure(&shar->work, alloc_len) == NULL)
                __archive_errx(1, "Out of memory");

        buf = shar->work.s + shar->work.length;
        *buf++ = UUENC(len);
        while (len >= 3) {
                uuencode_group(inbuf, buf);
                len -= 3;
                inbuf += 3;
                buf += 4;
        }
        if (len != 0) {
                tmp_buf[0] = inbuf[0];
                if (len == 1)
                        tmp_buf[1] = '\0';
                else
                        tmp_buf[1] = inbuf[1];
                tmp_buf[2] = '\0';
                uuencode_group(inbuf, buf);
                buf += 4;
        }
        *buf++ = '\n';
        if ((buf - shar->work.s) > (ptrdiff_t)(shar->work.length + 62))
                __archive_errx(1, "Buffer overflow");
        shar->work.length = buf - shar->work.s;
}
```

Indeed, tmp_buf gets set in lines 430-435, but in 436, where I'd expected it to be used, "buf" is used instead.

If this is correct or harmless, then maybe a compiler flag should be changed to avoid the "cc1: all warnings being treated as errors" feature.

Migrated from https://code.icecube.wisc.edu/ticket/650
```json
{
    "status": "closed", 
    "changetime": "2012-02-16T01:07:49", 
    "description": "$I3_PORTS/bin/port install libarchive\n\nresults in this error:\n{{{\n[ 47%] Building C object libarchive/CMakeFiles/archive.dir/archive_write_set_format_shar.c.o\n/home/boersma/Work/icetray/I3_PORTS/var/db/dports/build/file._home_boersma_Work_icetray_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_archivers_libarchive/work/libarchive-2.8.4/libarchive/archive_write_set_format_shar.c: In function \\u2018uuencode_line\\u2019:\n/home/boersma/Work/icetray/I3_PORTS/var/db/dports/build/file._home_boersma_Work_icetray_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_archivers_libarchive/work/libarchive-2.8.4/libarchive/archive_write_set_format_shar.c:412:7: error: variable \\u2018tmp_buf\\u2019 set but not used [-Werror=unused-but-set-variable]\ncc1: all warnings being treated as errors\n\nmake[2]: *** [libarchive/CMakeFiles/archive.dir/archive_write_set_format_shar.c.o] Error 1\nmake[1]: *** [libarchive/CMakeFiles/archive.dir/all] Error 2\nmake: *** [all] Error 2\n}}}\n\nThe offending lines of code does not seem to be completely harmless\n(quoting lines 411-443 of archive_write_set_format_shar.c):\n\n{{{\n#!C\n{\n        // char tmp_buf[3], *buf;\n        char tmp_buf[3], *buf;\n        size_t alloc_len;\n\n        /* len <= 45 -> expanded to 60 + len byte + new line */\n        alloc_len = shar->work.length + 62;\n        if (archive_string_ensure(&shar->work, alloc_len) == NULL)\n                __archive_errx(1, \"Out of memory\");\n\n        buf = shar->work.s + shar->work.length;\n        *buf++ = UUENC(len);\n        while (len >= 3) {\n                uuencode_group(inbuf, buf);\n                len -= 3;\n                inbuf += 3;\n                buf += 4;\n        }\n        if (len != 0) {\n                tmp_buf[0] = inbuf[0];\n                if (len == 1)\n                        tmp_buf[1] = '\\0';\n                else\n                        tmp_buf[1] = inbuf[1];\n                tmp_buf[2] = '\\0';\n                uuencode_group(inbuf, buf);\n                buf += 4;\n        }\n        *buf++ = '\\n';\n        if ((buf - shar->work.s) > (ptrdiff_t)(shar->work.length + 62))\n                __archive_errx(1, \"Buffer overflow\");\n        shar->work.length = buf - shar->work.s;\n}\n}}}\n\nIndeed, tmp_buf gets set in lines 430-435, but in 436, where I'd expected it to be used, \"buf\" is used instead.\n\nIf this is correct or harmless, then maybe a compiler flag should be changed to avoid the \"cc1: all warnings being treated as errors\" feature.\n", 
    "reporter": "boersma", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1329354469000000", 
    "component": "tools/ports", 
    "summary": "libarchive does not build with gcc 4.6.0", 
    "priority": "minor", 
    "keywords": "libarchive ports tools", 
    "time": "2011-09-01T16:29:56", 
    "milestone": "", 
    "owner": "nega", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20120216T01:07:49: 
* nega commented:

> fixed in 763


* nega changed description from:

> $I3_PORTS/bin/port install libarchive
> 
> results in this error:
> 
> [ 47%] Building C object libarchive/CMakeFiles/archive.dir/archive_write_set_format_shar.c.o
> /home/boersma/Work/icetray/I3_PORTS/var/db/dports/build/file._home_boersma_Work_icetray_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_archivers_libarchive/work/libarchive-2.8.4/libarchive/archive_write_set_format_shar.c: In function \u2018uuencode_line\u2019:
> /home/boersma/Work/icetray/I3_PORTS/var/db/dports/build/file._home_boersma_Work_icetray_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_archivers_libarchive/work/libarchive-2.8.4/libarchive/archive_write_set_format_shar.c:412:7: error: variable \u2018tmp_buf\u2019 set but not used [-Werror=unused-but-set-variable]
> cc1: all warnings being treated as errors
> 
> make[2]: *** [libarchive/CMakeFiles/archive.dir/archive_write_set_format_shar.c.o] Error 1
> make[1]: *** [libarchive/CMakeFiles/archive.dir/all] Error 2
> make: *** [all] Error 2
> 
> The offending lines of code does not seem to be completely harmless
> (quoting lines 411-443 of archive_write_set_format_shar.c):
> 
> {
>         // char tmp_buf[3], *buf;
>         char tmp_buf[3], *buf;
>         size_t alloc_len;
> 
>         /* len <= 45 -> expanded to 60 + len byte + new line */
>         alloc_len = shar->work.length + 62;
>         if (archive_string_ensure(&shar->work, alloc_len) == NULL)
>                 __archive_errx(1, "Out of memory");
> 
>         buf = shar->work.s + shar->work.length;
>         *buf++ = UUENC(len);
>         while (len >= 3) {
>                 uuencode_group(inbuf, buf);
>                 len -= 3;
>                 inbuf += 3;
>                 buf += 4;
>         }
>         if (len != 0) {
>                 tmp_buf[0] = inbuf[0];
>                 if (len == 1)
>                         tmp_buf[1] = '\0';
>                 else
>                         tmp_buf[1] = inbuf[1];
>                 tmp_buf[2] = '\0';
>                 uuencode_group(inbuf, buf);
>                 buf += 4;
>         }
>         *buf++ = '\n';
>         if ((buf - shar->work.s) > (ptrdiff_t)(shar->work.length + 62))
>                 __archive_errx(1, "Buffer overflow");
>         shar->work.length = buf - shar->work.s;
> }
> 
> Indeed, tmp_buf gets set in lines 430-435, but in 436, where I'd expected it to be used, "buf" is used instead.
> 
> If this is correct or harmless, then maybe a compiler flag should be changed to avoid the "cc1: all warnings being treated as errors" feature.

to:

> $I3_PORTS/bin/port install libarchive
> 
> results in this error:
> {{{
> [ 47%] Building C object libarchive/CMakeFiles/archive.dir/archive_write_set_format_shar.c.o
> /home/boersma/Work/icetray/I3_PORTS/var/db/dports/build/file._home_boersma_Work_icetray_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_archivers_libarchive/work/libarchive-2.8.4/libarchive/archive_write_set_format_shar.c: In function \u2018uuencode_line\u2019:
> /home/boersma/Work/icetray/I3_PORTS/var/db/dports/build/file._home_boersma_Work_icetray_I3_PORTS_var_db_dports_sources_rsync.code.icecube.wisc.edu_icecube-tools-ports_archivers_libarchive/work/libarchive-2.8.4/libarchive/archive_write_set_format_shar.c:412:7: error: variable \u2018tmp_buf\u2019 set but not used [-Werror=unused-but-set-variable]
> cc1: all warnings being treated as errors
> 
> make[2]: *** [libarchive/CMakeFiles/archive.dir/archive_write_set_format_shar.c.o] Error 1
> make[1]: *** [libarchive/CMakeFiles/archive.dir/all] Error 2
> make: *** [all] Error 2
> }}}
> 
> The offending lines of code does not seem to be completely harmless
> (quoting lines 411-443 of archive_write_set_format_shar.c):
> 
> {{{
> #!C
> {
>         // char tmp_buf[3], *buf;
>         char tmp_buf[3], *buf;
>         size_t alloc_len;
> 
>         /* len <= 45 -> expanded to 60 + len byte + new line */
>         alloc_len = shar->work.length + 62;
>         if (archive_string_ensure(&shar->work, alloc_len) == NULL)
>                 __archive_errx(1, "Out of memory");
> 
>         buf = shar->work.s + shar->work.length;
>         *buf++ = UUENC(len);
>         while (len >= 3) {
>                 uuencode_group(inbuf, buf);
>                 len -= 3;
>                 inbuf += 3;
>                 buf += 4;
>         }
>         if (len != 0) {
>                 tmp_buf[0] = inbuf[0];
>                 if (len == 1)
>                         tmp_buf[1] = '\0';
>                 else
>                         tmp_buf[1] = inbuf[1];
>                 tmp_buf[2] = '\0';
>                 uuencode_group(inbuf, buf);
>                 buf += 4;
>         }
>         *buf++ = '\n';
>         if ((buf - shar->work.s) > (ptrdiff_t)(shar->work.length + 62))
>                 __archive_errx(1, "Buffer overflow");
>         shar->work.length = buf - shar->work.s;
> }
> }}}
> 
> Indeed, tmp_buf gets set in lines 430-435, but in 436, where I'd expected it to be used, "buf" is used instead.
> 
> If this is correct or harmless, then maybe a compiler flag should be changed to avoid the "cc1: all warnings being treated as errors" feature.
> 


* nega changed resolution from "" to "fixed"
* nega changed status from "new" to "closed"
