### ISSUE TITLE
I3TRandomService does not compile with ROOT 6.05/02 (Trac #1363)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1355]
Compiling I3TRandomService 
- in offline-software release V15-08-00
- configured with cmake -DSYSTEM_PACKAGES=True
- and ROOT 6.05/02 installed from source into /usr/local/
- on Linux Mint 17.2, with GCC 4.8.4-2ubuntu1~14.04 and matching libstdc++
gives the error

```text
In file included from /usr/local/include/TNamed.h:29:0,
                 from /usr/local/include/TRandom.h:26,
                 from /usr/local/include/TRandom3.h:26,
                 from /home/chris/Software/offline/src/phys-services/public/phys-services/I3TRandomService.h:5,
                 from /home/chris/Software/offline/src/phys-services/private/phys-services/I3TRandomService.cxx:11:
/usr/local/include/TString.h:787:32: error: ‘string_view’ in namespace ‘std’ does not name a type
   std::string printValue(const std::string_view &val);
```

(full error message attached)

Migrated from https://code.icecube.wisc.edu/ticket/1363
```json
{
    "status": "closed", 
    "changetime": "2015-09-22T13:28:23", 
    "description": "Compiling I3TRandomService \n- in offline-software release V15-08-00\n- configured with cmake -DSYSTEM_PACKAGES=True\n- and ROOT 6.05/02 installed from source into /usr/local/\n- on Linux Mint 17.2, with GCC 4.8.4-2ubuntu1~14.04 and matching libstdc++\ngives the error\n\n{{{\nIn file included from /usr/local/include/TNamed.h:29:0,\n                 from /usr/local/include/TRandom.h:26,\n                 from /usr/local/include/TRandom3.h:26,\n                 from /home/chris/Software/offline/src/phys-services/public/phys-services/I3TRandomService.h:5,\n                 from /home/chris/Software/offline/src/phys-services/private/phys-services/I3TRandomService.cxx:11:\n/usr/local/include/TString.h:787:32: error: \u2018string_view\u2019 in namespace \u2018std\u2019 does not name a type\n   std::string printValue(const std::string_view &val);\n}}}\n\n(full error message attached)", 
    "reporter": "chraab", 
    "cc": "", 
    "resolution": "wontfix", 
    "_ts": "1442928503192644", 
    "component": "combo core", 
    "summary": "I3TRandomService does not compile with ROOT 6.05/02", 
    "priority": "normal", 
    "keywords": "offline,root,std,string_view", 
    "time": "2015-09-22T09:40:23", 
    "milestone": "", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150922T09:40:46: 
* chraab changed attachment from "" to "oh_dear_what_did_i_do_wrong_now"
* chraab commented:

> full stderr output

**Comment by icecube-trac** [comment]
Trac update at 20150922T13:28:23: 
* nega commented:

> sorry chraab, in slack i meant current ROOT v5.


* nega changed resolution from "" to "wontfix"
* nega changed status from "new" to "closed"
